version: '3.7'

services:
  mysqlmaster1:
    #hostname: 'mysqlmaster1'
    image: 'mysql:5.7'
    networks:
      - mysqlnet
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./config/mysql-master1:/etc/mysql/conf.d/
      - ./tool-config.toml:/tmp/tool-config.toml
      - ~/go/bin/linux_amd64/mysqlclusterinit:/tmp/mysqlclusterinit
  mysqlmaster2:
    #hostname: 'mysqlmaster2'
    image: 'mysql:5.7'
    ports:
      - 33062:3306
    networks:
      - mysqlnet
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./config/mysql-master2:/etc/mysql/conf.d/
      - ./tool-config.toml:/tmp/tool-config.toml
      - ~/go/bin/linux_amd64/mysqlclusterinit:/tmp/mysqlclusterinit
  mysqlmaster3:
    image: 'mysql:5.7'
    networks:
      - mysqlnet
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./config/mysql-master2:/etc/mysql/conf.d/
      - ./tool-config.toml:/tmp/tool-config.toml
      - ~/go/bin/linux_amd64/mysqlclusterinit:/tmp/mysqlclusterinit
  ha1:
      image: haproxy:1.7-alpine
      networks:
        - mysqlnet
      volumes:
        - ./haproxy:/usr/local/etc/haproxy
        - ./tool-config.toml:/tmp/tool-config.toml
        - ~/go/bin/linux_amd64/mysqlclusterinit:/tmp/mysqlclusterinit
networks:
  mysqlnet:
    name: mysqlnet