Master1Addr    = "mm1" # Master1的网络地址
Master2Addr    = "mm2" # Master2的网络地址
SlaveAddrs     = [] # Slave的网络地址
Password       = "root"       # Root用户密码
Port         = 3306           # MySQL 端口号
#MySQLDumpCmd = "./mysqldump"  # mysqldump命令路径，默认mysqldump
#MySQLCmd     = "./mysql"      # mysql命令路径，默认mysql
ReplUsr      = "repl"         # 复制用用户名，默认repl
ReplPassword = ""             # 复制用户密码，不指定则自动生成
Debug        = false          # 测试模式，只打印SQL和HAProxy配置, 不实际执行
LocalAddr      = ""             # 指定本机的网络地址，不指定则自动从网卡中获取
MySQLCnf     = "/etc/mysql/conf.d/my.cnf" # MySQL 配置文件的地址
MySQLRestartShell = "/etc/init.d/mysql restart" # MySQL重启命令, systemctl restart mysqld
HAProxyCfg   = "/usr/local/etc/haproxy/haproxy.cfg" # HAProxy配置文件地址
# HAProxyCfg   = "/etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg" # HAProxy配置文件地址
HAProxyRestartShell = "" # HAProxy重启命令
# HAProxyRestartShell = "systemctl restart haproxy" # HAProxy重启命令
# systemctl status haproxy
