Master1Addr         = "127.0.0.1"            # Master1的地址
Master2Addr         = "127.0.0.2"            # Master2的地址
SlaveAddrs          = []                          # Slave的地址列表
RootPassword        = "8BE4-62A56623CA8c"             # Root用户密码
Port                = 3306                        # MySQL 端口号
ReplUsr             = "repl"                      # 复制用用户名
ReplPassword        = "97c0-009CDF5C5816"             # 复制用户密码
MySQLCnf            = "/etc/my.cnf"               # MySQL 配置文件的地址

HAProxyCfg          = "/etc/haproxy.cfg"          # HAProxy配置文件地址
HAProxyRestartShell = "systemctl restart haproxy" # HAProxy重启命令

Debug               = false                       # 测试模式，只打印SQL和HAProxy配置, 不实际执行
LocalAddr           = ""                          # 指定本机地址，不指定则自动从网卡中获取

